### ISSUE TITLE
Releases need to be created for each new rsi editor version

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/RSIEdit#14]
Compiling it is cool but downloading it is even cooler

**Comment by SweptWasTaken** [comment]
Just make a GitHub Action

**Comment by SweptWasTaken** [comment]
EL STUPIDO

**Comment by DrSmugleaf** [comment]
Done since https://github.com/space-wizards/RSIEdit/commit/b47b3baabf8b2780cd456335eebd340848b4ac77
