### ISSUE TITLE
Frames are resized and reconverted to bitmaps every time the selected state changes

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/RSIEdit#15]
This is bad for the computer.

https://github.com/space-wizards/RSIEdit/blob/09066d1dc05936ad5a8de6902a3aef0461482e42/Editor/ViewModels/RsiItemViewModel.cs#L379

**Comment by mirrorcult** [comment]
this makes multiple selection SLOW AS FUCK

**Comment by DrSmugleaf** [comment]
Fixed looping every selected state when refreshing frames in https://github.com/space-wizards/RSIEdit/commit/aad4c0ecd4b50f7de5ba6f9f43b5ca2d16a0a0ad, the performance impact doesn't really matter when selecting single states
