### ISSUE TITLE
RSIEdit fails to succesfully import images from a DMI file

### ISSUE THREAD

**Issue by WlarusFromDaSpace** [space-wizards/RSIEdit#35]
When importing a DMI file RSIEdit fails to import it fully

screenshot: https://imgur.com/a/A1LJUFS

RSIEdit was built on OpenSUSE Tumbleweed using dotnet version 6.0.101 from microsofts' official production repository for OpenSUSE

**Comment by Willhelm53** [comment]
I've seen this too on DMI's grabbed from Goonstation.

**Comment by mirrorcult** [comment]
this happens for sufficiently large DMIs, here's an example DMI where it fails:

[critter.zip](https://github.com/space-wizards/RSIEdit/files/8103444/critter.zip)

**Comment by Willhelm53** [comment]
Ah yes thanks Mirror, I should've added that detail. For anyone watching, the critter.dmi is the one that prompted my comment. Another one I've seen it on is "objects.dmi"

[objects.zip](https://github.com/space-wizards/RSIEdit/files/8103458/objects.zip)

![image](https://user-images.githubusercontent.com/97707302/154829005-92ed15af-bfcb-4b85-b6f6-617607264da4.png)

**Comment by mirrorcult** [comment]
last working version is v0.1.5, so this was likely caused by the .NET 6 move. i think ss14 had a similar issue where imagesharp shit broke after .NET 6, so i'll look at that
